spring.application.name=QuanLyPhongGym

# ================= DATABASE =================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# =================SEND MAIL =================
sendgrid.api.key=${SENDGRID_API_KEY}
email.from=${EMAIL_FROM}



# =================SPRING MAIL =================
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}

spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}




# ================= SMS =================


# ================= MOMO PAYMENT =================
## DEV ENV

momo.endpoint=${DEV_MOMO_ENDPOINT}
momo.accessKey=${DEV_ACCESS_KEY}
momo.secretKey=${DEV_SECRET_KEY}
momo.partnerCode=${DEV_PARTNER_CODE}

momo.redirectUrl=${MOMO_REDIRECT_URL}
momo.ipnUrl=${MOMO_IPN_URL}


# ================= VNPAY PAYMENT =================
## Sandbox

## Callback
vnpay.payUrl=${VNPAY_PAYURL}
vnpay.returnUrl=${VNPAY_RETURN_URL}
vnpay.ipnUrl=${VNPAY_IPNURL}

## Version
vnpay.version=2.1.0
vnpay.command=pay
vnpay.currCode=VND
vnpay.locale=vn
vnpay.orderType=other

# ================= GEMINI/GROQ =================
groq.api-key=${GROQ_API_KEY}

# ================= SERVER =================
server.port=${PORT:8080}
